### PR TITLE
This is v0.11.0

### PR DESCRIPTION
**Pull request by bukzor**

### CODE REVIEW

**Comment by asottile** [comment]
The last change was barely a bugfix, 0.11.0 implies breaking probably

**Comment by asottile** [comment]
Also way to wait before merging :(

**Comment by bukzor** [comment]
All bumps during v0 are major, imply backwards incompatibility.

**Comment by asottile** [comment]
There is no backwards incompatibility here.  0.10.1 would have been a more appropriate version

**Comment by bukzor** [comment]
They're equally inappropriate; all bumps before v1 are major.

**Comment by asottile** [comment]
I disagree.  But it's too late now you already merged without waiting for feedback

**Comment by bukzor** [comment]
It's not a matter of opinion. http://semver.org/

**Comment by asottile** [comment]
semver does not define what to do less than 1.0.0, only that semantic versioning begins at 1.0.0.  In my _opinion_, the most sensible thing to do is denote non-breaking changes less than version 1 by changing the patch version.  You may not agree with me, but I think that is the most reasonable thing to do.  I think if you surveyed people, they'd generally agree with that.

**Pull request merged**
